# Site settings
title: "Sougata Panda | সৌগত পণ্ডা"
description: "Academic Page, ISI Kolkata"
author: "Sougata Panda"

# Build settings
markdown: kramdown

# MathJax support
mathjax: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# URL settings
url: "https://sougata543.github.io"
baseurl: ""

